# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6b00c86ebe7f9298c1a253bce4081fb39ea3a5a85a28730fb00a21059fff1636cba162f0ea3409a2410dc15139ab697ce5aff0a2d5b41cdc83bbfd08f88963f

test:
  secret_key_base: a6f54923d5bdbdc2210bc2e115f30528cc1413bd98352c4a93a5389e3ee1961dfc06477850a23d5f17a3ba035464b93394ccb472fa068d6bdc6036720c2818f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
